LPD-35947
liferay-release/liferay-docker pull request #77
Opened 2024-12-17 13:02 UTC by kiwm

2024-12-26 23:59 UTC, natocesarrego requested changes

2024-12-26 23:59 UTC, natocesarrego commented on release/release_gold.sh
> +	sed -i "/${search_key}/a\	\\${new_key}=${new_value}" "build.properties"
@kiwm, isn't missing a `/` at the end of the first parameter?

2024-12-26 23:59 UTC, natocesarrego commented on release/release_gold.sh
> +		-q ".url")"
@kiwm, can you please add a tab here to be like the following?
```
	local pull_request_url="$(\
		gh pr view liferay-release:new_releases_branch \
		    --repo pyoo47/liferay-jenkins-ee \
		    --json url \
		    -q ".url")"
```

2024-12-26 23:59 UTC, natocesarrego commented on release/test-dependencies/actual.liferay-jenkins-ee.build.properties/build.properties
> +#
@kiwm, can you please keep in the `build.properties` just what is strictly necessary for running the new tests created by you successfully? Please see this [commit](https://github.com/liferay/liferay-docker/commit/e30b22390d0c4e69dd53c06fa248ba5d25850b86) to get some inspiration. :wink:

2024-12-26 23:59 UTC, natocesarrego commented on release/test_release_gold.sh
> +	lc_cd "${_PROJECTS_DIR}/liferay-portal-ee" 2>/dev/null
@kiwm, did you have the chance to see this [comment](https://github.com/liferay-release/liferay-docker/pull/69#discussion_r1885811290)?

2024-12-26 23:59 UTC, closed without merging

2025-01-06 11:32 UTC, kiwm commented on release/test_release_gold.sh
> +	lc_cd "${_PROJECTS_DIR}/liferay-portal-ee" 2>/dev/null
Yes, it is only on the liferay-portal-ee because if this test is not run locally, the liferay-portal-ee will not exist, so we will encounter an error. the liferay-docker image exists on GitHub Actions but the liferay-portal-ee don't.

2025-01-07 11:19 UTC, kiwm commented on release/release_gold.sh
> +				"${quarterly_release_branch_name}" \
In this case, it should be repeated because this function should work for other cases where the value is different.

2025-01-07 11:21 UTC, kiwm commented on release/release_gold.sh
> +	sed -i "/${search_key}/a\	\\${new_key}=${new_value}" "build.properties"
I don't think so, is working like this.